"""add post reactions

Revision ID: 11b3b3782096
Revises: 0786d0324929
Create Date: 2026-05-11 23:39:20.180747

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "11b3b3782096"
down_revision: Union[str, Sequence[str], None] = "0786d0324929"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_reactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column(
            "reaction_type",
            sa.Enum("HELPFUL", "SAME_HERE", "SAVED_MY_MONEY", name="reaction_type"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "post_id", name="uq_post_reactions_user_post"),
    )
    op.create_index(
        op.f("ix_post_reactions_post_id"), "post_reactions", ["post_id"], unique=False
    )
    op.create_index(
        op.f("ix_post_reactions_user_id"), "post_reactions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_post_reactions_user_id"), table_name="post_reactions")
    op.drop_index(op.f("ix_post_reactions_post_id"), table_name="post_reactions")
    op.drop_table("post_reactions")

    # Drop the PostgreSQL enum type left behind after dropping the table.
    reaction_type_enum = sa.Enum(
        "HELPFUL",
        "SAME_HERE",
        "SAVED_MY_MONEY",
        name="reaction_type",
    )
    reaction_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
