"""add product fail scores

Revision ID: 8e5ef15e8ed1
Revises: 09239133ebf4
Create Date: 2026-04-26 03:02:17.241350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5ef15e8ed1'
down_revision: Union[str, Sequence[str], None] = '09239133ebf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_fail_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('value_regret_score', sa.Integer(), nullable=False),
    sa.Column('description_mismatch_score', sa.Integer(), nullable=False),
    sa.Column('quality_disappointment_score', sa.Integer(), nullable=False),
    sa.Column('funniness_score', sa.Integer(), nullable=False),
    sa.Column('anger_score', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('calculation_version', sa.String(length=50), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.add_column('posts', sa.Column('currency', sa.String(length=3), server_default='GBP', nullable=False))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'currency')
    op.drop_table('product_fail_scores')
    # ### end Alembic commands ###
