"""add post verdicts

Revision ID: 98e12ad4c4a4
Revises: 11b3b3782096
Create Date: 2026-05-26 16:39:37.542795

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "98e12ad4c4a4"
down_revision: Union[str, Sequence[str], None] = "11b3b3782096"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_verdicts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column(
            "verdict_type",
            sa.Enum("AGREE", "DISAGREE", name="verdict_type"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "post_id", name="uq_post_verdicts_user_post"),
    )
    op.create_index(
        op.f("ix_post_verdicts_post_id"), "post_verdicts", ["post_id"], unique=False
    )
    op.create_index(
        op.f("ix_post_verdicts_user_id"), "post_verdicts", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_post_verdicts_user_id"), table_name="post_verdicts")
    op.drop_index(op.f("ix_post_verdicts_post_id"), table_name="post_verdicts")
    op.drop_table("post_verdicts")
    verdict_type_enum = sa.Enum(
        "AGREE",
        "DISAGREE",
        name="verdict_type",
    )
    verdict_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
